### ISSUE TITLE
[功能请求]: 在系统时间发生变更时重新从 NTP 服务器同步时间

### ISSUE THREAD

**Issue by kaokao221** [HelloWRC/ClassIsland#100]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

前情提要：我们班的班机很神奇，关机后概率性时间回零 （2013-1-1 00:00）。

### 想要实现或优化的功能

为了登希沃，需要手动同步 NTP 时间，由于 ClassIsland 的 NTP 工作基于求时间差运行，会导致系统时间校准后 ClassIsland 时间故障，故可以考虑在侦测到系统时间变化时先不刷新主窗口，而是再次同步时间后刷新。

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by Misaka2298** [comment]
建议加一个开关
因为在本地调试时间表的过程中会多次手动修改系统时间（本人是这样的，用来测试课表效果），如果强制同步ntp时间的话可能会给调试带来不必要的麻烦

**Comment by HelloWRC** [comment]
已实现。
