### ISSUE TITLE
[功能请求]: 全局时间偏移

### ISSUE THREAD

**Issue by KremeCN** [HelloWRC/ClassIsland#101]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

我校的广播铃声不进行联网校时，较 NTP 快 37s，想要将 ClassIsland 的时间调快，以达到和铃声同步。

### 想要实现或优化的功能

添加全局时间偏移选项。

**Comment by Doctor-yoi** [comment]
您好！您的建议已经收到，在该功能未推送至master分支或dev分支前，您可以将课表整体向前偏移37秒以达到您的需求🤝

**Comment by KremeCN** [comment]
刚看到此功能已加入 Pre-Release 版本，本 issue 将被关闭。
