### ISSUE TITLE
[功能请求]: “贡献人员”自动更新

### ISSUE THREAD

**Issue by jiangyin-srinternet** [HelloWRC/ClassIsland#102]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

翻看关于页面看到的

### 想要实现或优化的功能

![屏幕截图 2024-04-24 141541](https://github.com/HelloWRC/ClassIsland/assets/149371019/ee21bc9a-ab8f-4c82-bd0d-f76a33a80f34)

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by HelloWRC** [comment]
@all-contributors please add @HelloWRC  for code

**Comment by HelloWRC** [comment]
@all-contributors 
please add @HelloWRC for code, doc, ideas, maintenance, design. 
please add @Doctor-yoi for code.
please add @jiangyin14 for doc, ideas.
please add @allcontributors for doc.
please add @fossabot for infra.
