### ISSUE TITLE
[Bug]: 在即将上课提醒时清除所有提醒后不提醒上课

### ISSUE THREAD

**Issue by LiuYan-xwx** [HelloWRC/ClassIsland#106]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1. 等待即将上课提醒特效弹出
2. 在提醒即将上课时，使用软件自带的清除所有提醒功能
3. 上课时间到时，提醒不弹出

### 期望的行为

上课提醒正确弹出

### 实际结果

上课提醒并未弹出，我认为清除所有提醒指的是当前的"即将上课"的提醒，而后的上课提醒应该不受影响

### 应用版本

1.3.3.1-83d2987

### 操作系统版本

Windows11 23H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by jiangyin-srinternet** [comment]
未能复现此bug，可能是概率性问题？请检查您的课程表配置

**Comment by HelloWRC** [comment]
感谢您的反馈，这个应该是一个设计缺陷。在发出即将上课提醒时，会将当前课程的上课提醒一并附加到提醒队列中，以实现在即将上课提醒结束后显示上课提醒，并不会单独发送上课提醒。而在显示即将上课提醒时清除所有提醒，会将当前的提醒和将要上课提醒一起清除，故在上课时不会再发送提醒。

目前我将考虑优化即将上课提醒的显示逻辑，使清除即将上课提醒时不会影响上课提醒。

**Comment by HelloWRC** [comment]
已修复。
