### ISSUE TITLE
[Bug]: 不加入管理的情况下，仍然显示来自集控服务器的提醒

### ISSUE THREAD

**Issue by CNwenwen** [HelloWRC/ClassIsland#116]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1.打开设置
2.转到提醒选项卡

### 期望的行为

集控服务器的提醒不可见

### 实际结果

![屏幕截图 2024-05-05 140337](https://github.com/HelloWRC/ClassIsland/assets/121096061/470afd9e-9497-463b-94e0-8f4e6d3589a6)

### 应用版本

1.3.4。0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
感谢您的反馈。

**Comment by HelloWRC** [comment]
已修复。
