### ISSUE TITLE
[功能请求]: 为安装更新时 下载的文件添加md5验证

### ISSUE THREAD

**Issue by dfh3913** [HelloWRC/ClassIsland#131]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

触发情况：网络问题致下载时在进度条的最后卡住，故我在下载进度条约百分之90处点击了取消更新，随后又点击了下载更新 此时应用提示您已准备好安装更新 点击重启后并安装更新 报错 如图所示
![image](https://github.com/HelloWRC/ClassIsland/assets/105592234/cd766d45-f5a3-48bf-b200-0bf5188635d4)
 此时 如果选择了在下次应用启动时安装更新 和报错里的重启应用 就会在第二次启动时完全卡住 报错如图 
![image](https://github.com/HelloWRC/ClassIsland/assets/105592234/93e981cf-17b7-4081-86ac-027ed26b0d5f)

### 想要实现或优化的功能

同标题

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by HelloWRC** [comment]
已实现。
