### ISSUE TITLE
集控功能

### ISSUE THREAD

**Issue by HelloWRC** [HelloWRC/ClassIsland#43]
允许从指定的url拉取应用设置策略清单，然后从策略清单指定的url拉取档案、设置和限制策略，并与本地合并。

- [x] 加载集控配置
  - [x] 从json文件加载
  - [ ] 从注册表加载
  - [x] 在欢迎向导加载
- [x] 集控说明UI
- [x] 资源获取url模板支持
- [x] 拉取档案
- [x] 拉取默认设置
- [x] 拉取限制策略
- [x] [与服务器通信，接受集控服务器指令](https://github.com/HelloWRC/ClassIsland.ManagementServer/issues/1)

**Comment by jiangyin14** [comment]
其实 最好是能在客户端和服务端之间建立连接，服务端暴露API接口，基于暴露的接口来开发集控系统（比如WebUI）
Feat.：从WebUI或者其他位置，向指定设备顶部课表栏群发通知信息

**Comment by jiangyin14** [comment]
应该在release中包含一个Setting.json文件，以供集控管理员修改构建。

**Comment by HelloWRC** [comment]
这里的`Settings.json`是指应用设置还是集控客户端配置？集控客户端配置在https://github.com/HelloWRC/ClassIsland/wiki/%E9%9B%86%E6%8E%A7%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6有参考文档，可以按照这个文档编辑；应用设置可以直接复制应用目录下的设置json文件。

________________________________
发件人: 姜胤 ***@***.***>
发送时间: 2024年3月25日 17:19
收件人: HelloWRC/ClassIsland ***@***.***>
抄送: HelloWRC ***@***.***>; Author ***@***.***>
主题: Re: [HelloWRC/ClassIsland] 集控功能 (Issue #43)

应该在release中包含一个Setting.json文件，以供集控管理员修改构建。

―

**Comment by jiangyin14** [comment]
> 这里的`Settings.json`是指应用设置还是集控客户端配置？集控客户端配置在https://github.com/HelloWRC/ClassIsland/wiki/%E9%9B%86%E6%8E%A7%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6 有参考文档，可以按照这个文档编辑；应用设置可以直接复制应用目录下的设置json文件。
> 

我再看“帮助”的时候，发现了参考文档，自己构建了json文件，谢谢
