### ISSUE TITLE
提醒语音播报

### ISSUE THREAD

**Issue by HelloWRC** [HelloWRC/ClassIsland#44]
在`NotificationRequest`中添加`MaskSpeechText`和`OverlaySpeechText`属性，对应在不同状态下要朗读的文本。

**Comment by jiangyin14** [comment]
在播放大于等于一小时的时间时不发出声音，请re-open本issue修补

**Comment by HelloWRC** [comment]
> 在播放大于等于一小时的时间时不发出语音

我这边没法复现这个问题。这个播放不出来的时间具体是多长？
