### ISSUE TITLE
在播放大于等于一小时的时间时不发出语音

### ISSUE THREAD

**Issue by jiangyin14** [HelloWRC/ClassIsland#51]
> 在播放大于等于一小时的时间时不发出语音

我这边没法复现这个问题。这个播放不出来的时间具体是多长？

_最初由 @HelloWRC 在 https://github.com/HelloWRC/ClassIsland/issues/44#issuecomment-2027866369 发布_

@HelloWRC 

01:00:00

**Comment by HelloWRC** [comment]
已修复
