### ISSUE TITLE
[新功能]希望能够在上下课是添加声音提醒，叮一下也行。

### ISSUE THREAD

**Issue by kaokao221** [HelloWRC/ClassIsland#53]

**Comment by kaokao221** [comment]
1. 声音提醒
  - 个人认为可以在`MainWindow.xaml.cs`的340行加一个声音事件（你问我为什么不自己写？1 不会写C# 2 这条issue甚至是班上一体机发的）
  - 声音用短而干脆的叮一声个人认为会比长铃声更好（而且学校有铃虽然但是偶尔没有）
2.

**Comment by HelloWRC** [comment]
感谢您的建议。第一条和 #41 重复了；第二条将会考虑实现。
