### ISSUE TITLE
时间校准功能

### ISSUE THREAD

**Issue by DavisZ327** [HelloWRC/ClassIsland#55]
学校铃声与标准时间存在一定偏差 建议可根据实际情况调整整体课表时间偏移

**Comment by jiangyin14** [comment]
我的解决方案：与学校信息中心/教务协商，在铃声服务器上开放NTP授时服务，使用ClassIsland v1.4.2.0的NTP校时功能同步时间。

**Comment by DavisZ327** [comment]
跟学校沟通这种事情……可能有点困难

**Comment by HelloWRC** [comment]
> 我的解决方案：与学校信息中心/教务协商，在铃声服务器上开放NTP授时服务，使用ClassIsland v1.4.2.0的NTP校时功能同步时间。

这个方案对于一些学校可能比较困难。根据测试，如果使用公共NTP服务，仍然会存在一定的延迟，但延迟基本趋于稳定。可以在加入NTP时间校准功能的同时加入时间偏移功能，便于微调时间。

**Comment by jiangyin14** [comment]
👍

**Comment by HelloWRC** [comment]
已实现。
