### ISSUE TITLE
如何导出配置好的课表？

### ISSUE THREAD

**Issue by meiyoushuru** [HelloWRC/ClassIsland#57]
我在家中电脑上配置好了时间表、课表和科目，我该如何将其导入到学校里的电脑上？

**Comment by jiangyin14** [comment]
在ClassIsland目录下的profiles文件夹内的Default.json就是课表文件，与学校电脑上的同级同文件做替换即可

**Comment by meiyoushuru** [comment]
> 在ClassIsland目录下的profiles文件夹内的Default.json就是课表文件，与学校电脑上的同级同文件做替换即可

感谢解答
