### ISSUE TITLE
建议增加时间校正功能

### ISSUE THREAD

**Issue by meiyoushuru** [HelloWRC/ClassIsland#58]
考虑到大多数学校响铃的时间并不准确且每天都有偏差，为避免课表显示时间与学校响铃时间不匹配，建议作者您考虑增加一个校正时间的功能，具体建议如下：
增加一个时间校正选项卡，包含以下可调参数
1. 校正秒数  允许用户输入一个时间秒数，ClassIsland将在调用系统时间时加上或减去该秒数，该操作立即生效
2. 每日自动叠加校正  允许用户输入一个时间秒数（精确到毫秒），ClassIsland 每日将在**校正秒数**的基础上加上或减去该秒数，该操作将在设置后的每个二十四点生效

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by jiangyin14** [comment]
参看#55

**Comment by HelloWRC** [comment]
功能1在#55已经实现，功能2目前可以考虑。不过在#47已经实现了从NTP服务器自动同步精确时间的功能，可以考虑与学校协调在在铃声服务器上开放授时服务来同步时间。

**Comment by meiyoushuru** [comment]
> 功能1在 #55 已经实现，功能2目前可以考虑。不过在 #47 已经实现了从NTP服务器自动同步精确时间的功能，可以考虑与学校协调在在铃声服务器上开放授时服务来同步时间。

恕我眼拙，请问该功能具体在哪个选项卡中

**Comment by HelloWRC** [comment]
这个功能目前已经加入测试版，但还没下放到稳定通道中。您可以在【更新】选项卡中将通道切换到测试通道，来使用这个功能。

**Comment by meiyoushuru** [comment]
> 这个功能目前已经加入测试版，但还没下放到稳定通道中。您可以在【更新】选项卡中将通道切换到测试通道，来使用这个功能。

我在测试版中也没有找到该功能，请问在哪里？

**Comment by meiyoushuru** [comment]
> 这个功能目前已经加入测试版，但还没下放到稳定通道中。您可以在【更新】选项卡中将通道切换到测试通道，来使用这个功能。

请问测试版中手动校正时间的功能在哪里呢？谢谢！

**Comment by HelloWRC** [comment]
抱歉，疏忽了，虽然手动调整时间偏移已经开发好了，还没有发布。预计会在这周到下周和其它做好的功能一起发到测试版。

**Comment by meiyoushuru** [comment]
> 抱歉，疏忽了，虽然手动调整时间偏移已经开发好了，还没有发布。预计会在这周到下周和其它做好的功能一起发到测试版。

感谢！我们学校的钟不准，迫切地需要以上功能，还请尽快更新发布，感谢！

**Comment by HelloWRC** [comment]
自动调整时间偏移功能已实现。
