### ISSUE TITLE
[功能请求]: 在最左测或最右侧显示倒数天数计数&一些附加信息

### ISSUE THREAD

**Issue by Youwenqwq** [HelloWRC/ClassIsland#60]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

个人使用过程中，老师提的两点建议：1.可以显示当日值日生情况 2.可以显示距离某次考试的倒计时
实现这两个功能之后可以不需要再在黑板上手动书写了

### 想要实现或优化的功能

在主界面最左侧或最右侧空白部分追加一块地方，用于显示倒计时。形式为“xx天”，“距离xx剩xx天”等等
用于显示附加信息：可以是可自定义的文本区域，或者导入一个顺序名单，每过一天读取下一个数据

**Comment by jiangyin14** [comment]
感谢您的建议。

**Comment by Doctor-yoi** [comment]
@HelloWRC 已发起实现该功能的pr，请及时查看

**Comment by HelloWRC** [comment]
#95 已实现。
