### ISSUE TITLE
科目编辑无效，显示缺失

### ISSUE THREAD

**Issue by meiyoushuru** [HelloWRC/ClassIsland#62]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

我尝试编辑科目，例如增加和删减科目，或者清空科目并按照自己喜欢的顺序录入

### 期望的行为

编辑后的科目应当正确显示，并可在时间表和课表中被选择（实际上却没有）

### 实际结果

在编辑完成后，科目未能正确显示，且顺序被打乱。我编辑的科目全部变成空白
![屏幕截图 2024-04-05 205726](https://github.com/HelloWRC/ClassIsland/assets/153412047/660cd5e3-0546-41d7-9833-92acbb3cddb5)

### 应用版本

1.3.2.0-Firely-adf601c(HEAD)

### 操作系统版本

Windows 11 23H2 22631.3374

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
感谢您的反馈。

**Comment by HelloWRC** [comment]
请问能更详细地说一下您是怎么遇到这个bug的吗，比如您具体是怎么进行编辑的。可以附上操作时的录屏附件。

**Comment by meiyoushuru** [comment]
> 请问能更详细地说一下您是怎么遇到这个bug的吗，比如您具体是怎么进行编辑的。可以附上操作时的录屏附件。

录屏视频太大无法发送，您可以提供邮箱吗？

**Comment by HelloWRC** [comment]
> > 请问能更详细地说一下您是怎么遇到这个bug的吗，比如您具体是怎么进行编辑的。可以附上操作时的录屏附件。
> 
> 录屏视频太大无法发送，您可以提供邮箱吗？

mchwrc_sharper@outlook.com

**Comment by HelloWRC** [comment]
已成功复现bug，具体表现为：如果在编辑状态下（焦点在单元格文本框中时）连续点击【添加】按钮添加科目，那么会出现科目信息丢失的问题。如果不是处于编辑状态下连续点击【添加】按钮添加科目，虽然科目信息不会丢失，但科目顺序会颠倒。

目前有一个临时的解决方案：在添加科目时先不要使用【添加】按钮，而是直接在最下面的空行上填写新的科目信息。填完一个空行后按回车会生成新的空行，可以继续填写。

![image](https://github.com/HelloWRC/ClassIsland/assets/55006226/6dca4ceb-aa77-4bea-a087-596a39f38271)

![image](https://github.com/HelloWRC/ClassIsland/assets/55006226/c74e999b-9d14-47d4-a52c-c90524310b0d)

**Comment by HelloWRC** [comment]
根据排查，目前确定顺序混乱是由存储科目信息的类型`Dictionary<TKey, TValue>`但机制引起的。在正常添加时不会有问题发生，但在删除科目后再添加科目，就可能会出现顺序混乱的问题。这种情况可能在以与科目相同方式存储的课表和时间表中都存在。

目前正在进一步调查科目消失的问题。

**Comment by HelloWRC** [comment]
已修复。目前在使用DataGrid编辑科目时，在编辑状态下点击工具栏上的【添加】按钮添加科目时，会自动退出编辑模式，但不会保留更改。目前经过测试，问题已经不会复现了。

但在删除一些科目后，新添加的科目顺序被打乱的问题是由存储科目的数据类型`Dictionary`自身引起的，这个问题将尝试在后面通过更改存储科目的数据类型修复。

**Comment by meiyoushuru** [comment]
> 已修复。目前在使用DataGrid编辑科目时，在编辑状态下点击工具栏上的【添加】按钮添加科目时，会自动退出编辑模式，但不会保留更改。目前经过测试，问题已经不会复现了。
> 
> 但在删除一些科目后，新添加的科目顺序被打乱的问题是由存储科目的数据类型`Dictionary`自身引起的，这个问题将尝试在后面通过更改存储科目的数据类型修复。

或许将 Dictionary 中的 key 用元组，增加一个作为排序的flag，可视化时sort一下再print？（（（

**Comment by HelloWRC** [comment]
> 或许将 Dictionary 中的 key 用元组，增加一个作为排序的flag，可视化时sort一下再print？（（（

这个方法理论上也是可以的，不过这个可能得等到后面的版本来实现了

**Comment by JustJoy122** [comment]
> > 或许将 Dictionary 中的 key 用元组，增加一个作为排序的flag，可视化时sort一下再print？（（（
> 
> 这个方法理论上也是可以的，不过这个可能得等到后面的版本来实现了

请问现在2.0.0新版本有可能实现排序吗 @HelloWRC

**Comment by HelloWRC** [comment]
> > > 或许将 Dictionary 中的 key 用元组，增加一个作为排序的flag，可视化时sort一下再print？（（（
> > 
> > 
> > 这个方法理论上也是可以的，不过这个可能得等到后面的版本来实现了
> 
> 请问现在2.0.0新版本有可能实现排序吗 [@HelloWRC](https://github.com/HelloWRC)

有可能。目前已经有相关议题提出了这个问题，但实现时间待定。
