### ISSUE TITLE
[功能请求]: 禁用准备上课提醒文字

### ISSUE THREAD

**Issue by Lyif233** [HelloWRC/ClassIsland#64]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

“准备上课提醒文字”一栏留空时（如图1），
![image](https://github.com/HelloWRC/ClassIsland/assets/150530146/dd27940c-f24d-4e5c-b04a-6ba3cf459d4e)
会出现完全空白的进度条（如图2）
![image](https://github.com/HelloWRC/ClassIsland/assets/150530146/91f4a7ee-9b0d-439a-b431-bd6e7a6cc03a)

### 想要实现或优化的功能

希望增设一个“禁用准备上课提醒文字”的选项，让进度条与倒计时流畅跑完
![image](https://github.com/HelloWRC/ClassIsland/assets/150530146/29d18aee-e264-44e5-9e3e-4260e5d76b77)

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by Lyif233** [comment]
谢谢！我还在思考，是否可以通过换行，列出多种提醒文字，供Classland随机选择？

**Comment by HelloWRC** [comment]
> 谢谢！我还在思考，是否可以通过换行，列出多种提醒文字，供Classland随机选择？

应该是可以的

**Comment by HelloWRC** [comment]
禁用准备上课提醒文字已实现

**Comment by jiangyin-srinternet** [comment]
疑似非默认开启，建议写为默认开启 @HelloWRC
