### ISSUE TITLE
显示时间点附加信息选项无效

### ISSUE THREAD

**Issue by meiyoushuru** [HelloWRC/ClassIsland#65]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

对 `应用设置-基本-显示时间点附加信息` 选项进行设置不起作用

### 期望的行为

根据设置，我应当可以选择在当前时间点上显示或者不显示附加信息，并可选择显示何种附加信息

### 实际结果

事实上，无论我如何设置该选项，都会显示并只能显示 `时间点持续时间` 这一默认附加信息，而无法更改
![屏幕截图 2024-04-05 074140](https://github.com/HelloWRC/ClassIsland/assets/153412047/bcebd23e-9357-4375-be7b-80939e286389)
![屏幕截图 2024-04-05 074154](https://github.com/HelloWRC/ClassIsland/assets/153412047/78c99455-00a2-421e-bbaa-b2e78b6d12a7)

### 应用版本

1.3.2.0-Firely-adf601c(HEAD)

### 操作系统版本

Windows 11 23H2 22631.3374

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
感谢您的反馈。

**Comment by HelloWRC** [comment]
我无法复现这个bug，请检查下在档案中有没有设置时间点附加信息选项相关的附加设置。如果没有调整过这些设置，那这个Bug确实有点玄乎。如果可以，请把应用目录下`Settings.json`（应用设置文件）和`Profiles\Default.json`（当前启用的档案）也一起发送过来，便于我排查问题，谢谢。

**Comment by kaokao221** [comment]
就个人经验来说，如果存在设置已经应用且保存的情况下仍然无法再主窗口中应用的话，可以尝试重新打开ClassIsland解决。

**Comment by meiyoushuru** [comment]
> 我无法复现这个bug，请检查下在档案中有没有设置时间点附加信息选项相关的附加设置。如果没有调整过这些设置，那这个Bug确实有点玄乎。如果可以，请把应用目录下`Settings.json`（应用设置文件）和`Profiles\Default.json`（当前启用的档案）也一起发送过来，便于我排查问题，谢谢。

我附的图片不对，我在科目中已经设置了时间点附加信息。但是`课间休息` 的时间点附加信息只能是 `持续时间`，而不受全局设置的影响。我该如何调整 ‘课间休息’的时间点附加信息？

**Comment by HelloWRC** [comment]
`课间休息` 类型的时间点目前不支持从科目层面上直接调节。如果您没有在时间点、时间表和课表这几个层级上设置过时间点附加信息相关选项的话，那么就会直接使用全局设置。

**Comment by meiyoushuru** [comment]
> `课间休息` 类型的时间点目前不支持从科目层面上直接调节。如果您没有在时间点、时间表和课表这几个层级上设置过时间点附加信息相关选项的话，那么就会直接使用全局设置。

我的意思是，我没有找到单独调节课间休息的 `时间点附加信息` 的选项，而调整全局设置对课间休息不起效果。

**Comment by HelloWRC** [comment]
> > `课间休息` 类型的时间点目前不支持从科目层面上直接调节。如果您没有在时间点、时间表和课表这几个层级上设置过时间点附加信息相关选项的话，那么就会直接使用全局设置。
> 
> 我的意思是，我没有找到单独调节课间休息的 `时间点附加信息` 的选项，而调整全局设置对课间休息不起效果。 

抱歉，单独调节课间休息的 `时间点附加信息` 这个功能确实没有实现。

调整全局设置对课间休息不起效果这个bug已经了解到了。如果可以的话，希望能够把设置文件和档案文件（`Settings.json`，`Profiles/Default.json`）都附上，便于我查找问题。

感谢您的反馈。

**Comment by meiyoushuru** [comment]
> > > `课间休息` 类型的时间点目前不支持从科目层面上直接调节。如果您没有在时间点、时间表和课表这几个层级上设置过时间点附加信息相关选项的话，那么就会直接使用全局设置。
> > 
> > 
> > 我的意思是，我没有找到单独调节课间休息的 `时间点附加信息` 的选项，而调整全局设置对课间休息不起效果。
> 
> 抱歉，单独调节课间休息的 `时间点附加信息` 这个功能确实没有实现。
> 
> 调整全局设置对课间休息不起效果这个bug已经了解到了。如果可以的话，希望能够把设置文件和档案文件（`Settings.json`，`Profiles/Default.json`）都附上，便于我查找问题。
> 
> 感谢您的反馈。

[Settings.json](https://github.com/HelloWRC/ClassIsland/files/14893855/Settings.json)
[Default.json](https://github.com/HelloWRC/ClassIsland/files/14893856/Default.json)

**Comment by HelloWRC** [comment]
根据检查，目前确认是在课表和科目层面上启用了特定课程显示设置，覆盖了应用的全局设置（如图），导致全局设置不生效。取消勾选以后，应用根据全局设置正常显示所选的附加信息。

![image](https://github.com/HelloWRC/ClassIsland/assets/55006226/97f524d0-0535-48e5-97ff-8d8a64e4316b)

![image](https://github.com/HelloWRC/ClassIsland/assets/55006226/6bf97c3b-b7bc-48bf-94a9-14d18d850a8a)

需要注意的是，只要勾选了“启用特定课程显示设置”，那么这一部分的设置会直接覆盖全局或上一层级的设置，即使保持这些选项为默认值。您可以把相关的课表和时间表都检查一遍，取消勾选“启用特定课程显示设置”选项。

**Comment by HelloWRC** [comment]
如果没别的问题的话我就关闭这个issue了。

**Comment by meiyoushuru** [comment]
> 如果没别的问题的话我就关闭这个issue了。

你好，我的表述和附图不当。我想反馈的问题是`课间休息`的`时间点附加信息`只能显示`持续时间`，而不是上课时的`时间点附加信息`只能显示`持续时间`。
`课间休息`的`时间点附加信息`是没有单独的调整选项的，请问它是根据全局设置来显示`时间点附加信息`，还是继承它的前一/后一课程？
目前，这个问题在某次重启后突然解决了，现在`课间休息`将根据全局设置来显示`时间点附加信息`。但是我并未对相关设置作任何改动，也即仍然保持我上传的`Settings.json`和`Default.json`，这令人感到匪夷所思。但至少问题解决了。

**Comment by HelloWRC** [comment]
`课间休息`类型的时间点会继承使用上一层级（时间点、课表、时间表）的时间点附加信息设置，如果这些地方都没有进行特定的设置，那么会直接使用全局设置。

**Comment by meiyoushuru** [comment]
> `课间休息`类型的时间点会继承使用上一层级（时间点、课表、时间表）的时间点附加信息设置，如果这些地方都没有进行特定的设置，那么会直接使用全局设置。

好的，我了解了，谢谢！
