### ISSUE TITLE
测试版更新后报错无法打开

### ISSUE THREAD

**Issue by meiyoushuru** [HelloWRC/ClassIsland#72]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

我在 `应用设置-更新` 中将测试版1.3.2.0更新至1.3.3.0

### 期望的行为

更新应当正常完成

### 实际结果

更新后，弹出报错，软件卡在加载界面无法打开
![屏幕截图 2024-04-06 151911](https://github.com/HelloWRC/ClassIsland/assets/153412047/79a763e1-9385-4e80-93b0-71e2c7216472)
报错信息如下
[System.IO.InvalidDataException End .txt](https://github.com/HelloWRC/ClassIsland/files/14892932/System.IO.InvalidDataException.End.txt)

### 应用版本

1.3.3.0-Firelt

### 操作系统版本

Windows 11 23H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
可能是更新下载损坏的问题。把软件目录下`UpdateTemp`文件夹完全删除后，再启动软件，下载更新试试。

**Comment by meiyoushuru** [comment]
> 可能是更新下载损坏的问题。把软件目录下`UpdateTemp`文件夹完全删除后，再启动软件，下载更新试试。

这并不起作用。我通过GitHub直接下载新的包，下载速度是正常的，但就是无法直接在软件中更新。

**Comment by HelloWRC** [comment]
已在 #131 添加了更新包验证，防止更新下载损坏。
