### ISSUE TITLE
[Bug]: 天气选择城市时无法找到所在县区

### ISSUE THREAD

**Issue by woshishei1993** [HelloWRC/ClassIsland#73]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

在天气中无法找到昆明市五华，盘龙，西山等县区，选择”昆明市”时无法正常显示天气预警

### 期望的行为

望作者增加天气数据源

### 实际结果

![微信图片_20240406204308](https://github.com/HelloWRC/ClassIsland/assets/137604592/e84ddd7b-be30-482e-a95c-0b0d4cce069f)

### 应用版本

1.3.0.2-Elysia-76acacf(HEAD)

### 操作系统版本

11.22631.3296

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by jiangyin-srinternet** [comment]
接入的天气api精度有限，建议选择最后一层精度，如县级以上市级

**Comment by HelloWRC** [comment]
很抱歉，这个问题没办法解决，因为调用的天气api有的收录的地区没有精准到县区级别。

您可以按您所在的区域选择提供的城市列表中最精准的城市。
