### ISSUE TITLE
[功能请求]: 临时课表持久化

### ISSUE THREAD

**Issue by jiangyin-srinternet** [HelloWRC/ClassIsland#75]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

调休时重启电脑需要再次设置临时课表，不方便。

### 想要实现或优化的功能

如题，在当日持久化选择固定课表，重启不影响，隔天恢复。

**Comment by meiyoushuru** [comment]
> ### 检查清单
> * [x]  我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
> * [x]  我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
> * [x]  我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。
> 
> ### 背景与动机
> 调休时重启电脑需要再次设置临时课表，不方便。
> 
> ### 想要实现或优化的功能
> 如题，在当日持久化选择固定课表，重启不影响，隔天恢复。

同求。可以给出选项，选择是重启恢复还是次日恢复。

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by Youwenqwq** [comment]
确实，考虑到临时课表一般会全天生效，而一日内由于学校电源策略等因素，教学电脑会关机重启数次导致临时课表失效，由此造成每次都需要管理员手动设置，非常麻烦，希望能够改进qwq

**Comment by HelloWRC** [comment]
已实现。

**Comment by jiangyin-srinternet** [comment]
回访：功能正常
