### ISSUE TITLE
[功能请求]: 在课表一侧增加倒计时

### ISSUE THREAD

**Issue by Misaka2298** [HelloWRC/ClassIsland#76]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

临近中高考，添加倒计时功能可以很方便的查看剩余时间

### 想要实现或优化的功能

在设置中修改倒计时截止日期，完成后在课表最右侧增加一个“n天”的倒计时

**Comment by kaokao221** [comment]
按照开发者意愿，可能会以插件形式提供，类似建议已进入 FUTURE 里程碑，短期可能不做重度考虑。

**Comment by HelloWRC** [comment]
与 #60 重复。
