### ISSUE TITLE
[功能请求]: 增加档案json在线拉取功能

### ISSUE THREAD

**Issue by Misaka2298** [HelloWRC/ClassIsland#77]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

对档案json进行修改往往是个很费时间的工作，如果在学校的下课10分钟完成显然太仓促，如果提前在家里写好然后用U盘拷贝覆盖又太过麻烦（一点都不优雅！），所以建议新增一个在线拉取json的功能，这样在家里修改完json之后第二天电脑启动就能读取新的档案了，十分甚至九分的优雅啊（赞赏

### 想要实现或优化的功能

在设置界面新增一个在线拉取json的可选项，内容为一个复选框（是否开启此功能）和一个json链接地址，json文件源可以用gitee（可以写在教程里面），然后如果勾选复选框的话就在每次启动时拉取一遍json并覆盖本地文件（建议本地文件同时备份一下，可以给5到6次的备份，反正这玩意也不大）然后读取

**Comment by jiangyin-srinternet** [comment]
Duplicated

已在#43基本实现（仍在完善）
功能已经推送到dev分支（1.3.2.0及更新版本）
具体使用方法见项目仓库Wiki中的 集控选项卡。
