### ISSUE TITLE
[功能请求]: 增加时间修正功能

### ISSUE THREAD

**Issue by Misaka2298** [HelloWRC/ClassIsland#78]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

众所周知，学校的铃声与真实的时间往往有数十秒甚至几分钟的时间差，这会导致铃声响起时课表上还在走60s倒计时，所以建议增加一个时间修正功能，让ClassIsland的时间对齐学校的恼谭闹铃

### 想要实现或优化的功能

在设置里新增一个时间修正项，数据类型为整型（这东西应该没必要用浮点吧草），设置完成后ClassIsland的时间表会根据此项的数据整体加速/减速
如：设置为30（s），那么本来设置为10:00:00-10:30:00的一节课会变为10:00:30-10:30:30
如设置为-30（s）那么本来设置为10:00:00-10:30:00的一节课会变为09:59:30-10:29:30
这里的时间修改不影响课表上显示的时间，即如上面的例子，原本设置的10:00-10:30还会显示为10:00-10:30而非修改后的时间

**Comment by kaokao221** [comment]
与 #58 重复，还请自行关闭（因为我不是开发者）
