### ISSUE TITLE
TSS朗读出错

### ISSUE THREAD

**Issue by jizilin6732** [HelloWRC/ClassIsland#79]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

我准备使用测试版的语音播报功能

### 期望的行为

出现了一些问题

### 实际结果

1. 选择第二个edge TSS，在朗读到课表中设置的天气预报时，会出现天气预报无法朗读然后，后面的上下课,距离上课提醒........等，无法朗读出来。出乎意料的是，选择系统自带的TSS时，天气预报还是无法朗读，但是其他的可以正常播放。
2. 天气预警的更多选项，中的所有开关，均无法保存我的更改
 ！以上是我尝试多次无法处理的问题！
![屏幕截图 2024-04-08 185856](https://github.com/HelloWRC/ClassIsland/assets/162853646/aa6b1225-ed6f-464d-b101-073224e61b23)
![屏幕截图 2024-04-08 185902](https://github.com/HelloWRC/ClassIsland/assets/162853646/6d07e3be-7135-4553-82fd-ec3a08e5270f)

### 应用版本

1.3.3.0-Firefly-d932a0c(HEAD)

### 操作系统版本

22634.3296

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by jiangyin-srinternet** [comment]
1.天气预报没有朗读功能。
2.感谢您的反馈，暂不能复现，将会持续跟进

**Comment by jizilin6732** [comment]
重新发
