### ISSUE TITLE
[Bug]: 天气无法刷新

### ISSUE THREAD

**Issue by CNwenwen** [HelloWRC/ClassIsland#83]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

在主菜单→应用设置→天气选项卡中，点击【刷新】。

### 期望的行为

应当刷新成当前时间的天气预报

### 实际结果

无法刷新
有可能是配置时的天气，有可能是【？】天气

### 应用版本

1.3.0.2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by CNwenwen** [comment]
> 感谢您的反馈，请提供出现错误时的日志。
> 
> 在关于页面点击应用logo十次后可以打开调试菜单，在调试菜单中勾选“调试终端”即可查看日志。

info: ClassIsland.Services.WeatherService[0]
      获取天气信息： https://weatherapi.market.xiaomi.com/wtr-v3/weather/all?latitude=110&longitude=112&locationKey=weathercn%3A101020100&days=15&appKey=weather20151024&sign=zUFJoAR2ZVrDy1vF3D07&isGlobal=false&locale=zh_cn
info: ClassIsland.Services.SettingsService[0]
      写入配置文件。
info: ClassIsland.Services.SettingsService[0]
      写入配置文件。

**Comment by HelloWRC** [comment]
根据日志，看起来应用已经成功获取到了天气信息。小米天气api的信息是每5分钟更新一次的，应用中显示的更新时间事实上是api侧的数据更新时间，不一定是在ClassIsland中刷新时的时间。

**Comment by CNwenwen** [comment]
> 根据日志，看起来应用已经成功获取到了天气信息。小米天气api的信息是每5分钟更新一次的，应用中显示的更新时间事实上是api侧的数据更新时间，不一定是在ClassIsland中刷新时的时间。

这是我在自己电脑（系统版本：Windows 11,23H2）的测试，在希沃大屏上（系统版本：Windows 10,20H2）的表现是完全不同的。

**Comment by HelloWRC** [comment]
那有可能网络问题。您可以在返校后再测试一下，并把产生的日志附到这个issue里。

**Comment by HelloWRC** [comment]
感谢您的反馈，根据日志，看起来是学校的网络问题。您可以试试单独把api链接粘贴到浏览器里访问，看看会不会报错。

**Comment by HelloWRC** [comment]
那这个可能更多的是您网络的问题。不过可以考虑在网络请求失败后重试请求来缓解这个问题。

**Comment by CNwenwen** [comment]
> 那这个可能更多的是您网络的问题。不过可以考虑在网络请求失败后重试请求来缓解这个问题。

怎么重试请求捏？

**Comment by HelloWRC** [comment]
> 怎么重试请求捏？

抱歉我的表述有点问题，我的意思是我计划在软件内添加请求失败后自动重试的功能。

**Comment by CNwenwen** [comment]
> > 怎么重试请求捏？
> 
> 抱歉我的表述有点问题，我的意思是我计划在软件内添加请求失败后自动重试的功能。

6的，那你加个计划罢
