### ISSUE TITLE
[Bug]: 户外课程“上课提醒”调整时间功能无效

### ISSUE THREAD

**Issue by CNwenwen** [HelloWRC/ClassIsland#87]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

设置一个课程为户外课程

### 期望的行为

在规定时间内显示上课提醒

### 实际结果

在刚下课时就显示上课提醒，并且怎么调时间都没用

### 应用版本

1.3.3.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by jizilin6732** [comment]
我好像也遇到了

**Comment by jiangyin14** [comment]
有可能在应用设置中被全局设置覆盖？请尝试修改

**Comment by HelloWRC** [comment]
感谢您的反馈。

**Comment by CNwenwen** [comment]
> 有可能在应用设置中被全局设置覆盖？请尝试修改

没改过时间表里的，都改的是全局设置
