### ISSUE TITLE
[功能请求]: 提醒特效低分辨率模式

### ISSUE THREAD

**Issue by HelloWRC** [HelloWRC/ClassIsland#88]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

一些大屏设备使用了4k分辨率的显示屏，但性能较弱，播放提醒特效时会出现严重的掉帧现象。理论上降低渲染时分辨率可以缓解这个问题，并且在远处观看时基本不影响显示效果。

### 想要实现或优化的功能

- [ ] 1. 在显示特效时降低分辨率，并提供此功能的开关。
- [ ] 2. 在分辨率大于1920x1080时自动开启此功能。

**Comment by jizilin6732** [comment]
😊😊😊

**Comment by jiangyin14** [comment]
👍👍👍

**Comment by HelloWRC** [comment]
已实现。
