### ISSUE TITLE
[Bug]:关于Windows7系统下的内存泄漏问题

### ISSUE THREAD

**Issue by yang932** [HelloWRC/ClassIsland#91]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

在Windows7系统中启动本软件时会出现严重的内存泄漏现象（具体表现为在4G设备下内存占用在数秒内迅速升至3.8G以上并卡死），该问题非本程序特有，而是在所有基于net8.0的程序均有该现象（如MaaAssistantArknights项目的#8238），且可以确定为“DotNet7/8 不再支持 win7/8 ，但可以“不受支持的运行””的缘故（详见https://github.com/dotnet/msbuild/issues/8404#issuecomment-1666903883）

### 期望的行为

无法解决，但应写入帮助文件以供他人了解

### 实际结果

该bug并不会导致程序无法在Windows7上使用（卡顿3分钟后可以正常启动），但会影响Windows7低内存设备的运行效果，如不适合开机自启动等

### 应用版本

1.3.0 2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by jiangyin-srinternet** [comment]
了解。晚点写入README.md

**Comment by HelloWRC** [comment]
感谢您的反馈。您可以尝试将ClassIsland降级到 [1.2.0.0](https://github.com/HelloWRC/ClassIsland/releases/tag/1.2.0.0) ，这个版本是基于 .NET 6 框架的。在降级完毕后，请记得关闭自动更新。

在 https://github.com/dotnet/runtime/issues/79469#issuecomment-1371202114 有一个针对Windows 7临时的解决方案，如果您想要继续使用 1.2.0.0 以上的版本，可以参考一下。

**Comment by HelloWRC** [comment]
已在 #93 完成修改并合并。

**Comment by Doctor-yoi** [comment]
已在commit_9baddd中修复，可以在明天从每日构建中下载master分支最新构建协助测试
