### ISSUE TITLE
课表经常卡住

### ISSUE THREAD

**Issue by meiyoushuru** [HelloWRC/ClassIsland#92]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

正常显示课表

### 期望的行为

正常显示课表

### 实际结果

课表会不定期突然卡住，在点击屏幕任意位置（而不是Banner）后恢复正常。
重新启动App和计算机均不能解决问题。
![屏幕截图 2024-04-16 082423](https://github.com/HelloWRC/ClassIsland/assets/153412047/bef90374-9fbb-41c4-856e-103ac72b2bff)

### 应用版本

1.3.3.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
感谢您的反馈。

**Comment by jiangyin-srinternet** [comment]
概率性复现 日志一切正常
![err1](https://github.com/HelloWRC/ClassIsland/assets/149371019/18538faf-48bf-4ba5-b1ea-6f2c6f44af7c)

截完屏就正常了，逆天......
![err2](https://github.com/HelloWRC/ClassIsland/assets/149371019/49659c39-5945-4b5c-8c3a-5b420fcb8b3c)

**Comment by HelloWRC** [comment]
根据测试，在进行以下操作后，也可以稳定复现这个问题：

- 锁定 Windows (<kbd>Win</kbd> + <kbd>L</kbd>)，然后解锁 Windows
- 运行一些特定应用（如QQ音乐等）

在出现这个问题后，虽然应用正常工作，但界面停止渲染。根据测试，在有应用进入或退出全屏后，界面渲染会恢复正常。这个问题似乎和WPF的渲染机制有关。

**Comment by HelloWRC** [comment]
目前此问题已修复，但在进行 https://github.com/HelloWRC/ClassIsland/issues/92#issuecomment-2066318019 所述的操作后仍然会有部分界面（如设置界面的外观和更新选项卡）停止渲染，并且此时应用内存占用会显著增加。

**Comment by HelloWRC** [comment]
目前理论上可以保证主界面不会卡住，如果在更新 [1.3.3.1](https://github.com/HelloWRC/ClassIsland/releases/tag/1.3.3.1) 后还能复现此问题，可以重新打开此 issue 继续反馈。
