### ISSUE TITLE
换课启用临时层后次日不会恢复

### ISSUE THREAD

**Issue by meiyoushuru** [HelloWRC/ClassIsland#94]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

我使用了换课功能

### 期望的行为

换课应只在当日内的本次启动有效，重启app或次日，课表应恢复正常。

### 实际结果

若 ClassIsland 保持运行，次日课表仍为前一日的临时课表。

### 应用版本

1.3.3.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
这个问题无法复现

**Comment by meiyoushuru** [comment]
> 这个问题无法复现

我们教室的电脑从不关机。我前一天如果换过课，第二天就仍然是前一天换过课的课表，重启 ClassIsland 后恢复正常。该情况已出现两次。
难道其实是那个界面卡住的bug？/笑哭
等我上学时尝试复现。

**Comment by LiuYan-xwx** [comment]
昨天我还出现了这个问题，不知道触发的

**Comment by HelloWRC** [comment]
已修复。
