### ISSUE TITLE
[Bug]: 意外的花屏现象

### ISSUE THREAD

**Issue by kaokao221** [HelloWRC/ClassIsland#99]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

重现挺难的，有一半是硬件问题

出现条件：
- 重复启动 ClassIsland 时 100% 花屏
- 启动 ClassIsland 时概率花屏

该现象在稳定版本中不会在启动时出现，只会在重复启动时出现，可以稍微排查一下，明天把硬件信息补上。

另外我们的一体机似乎使用 VNC 实现控制，可能跟 VNC 有关。

### 期望的行为

避免花屏现象

### 实际结果

还是经常花

### 堆栈跟踪（可选）

```shell
由于已经花屏，跟踪信息无法呈现，可以考虑写入 log 文件以重现日志。
```

### 应用版本

最后一个 Dev 版本

### 操作系统版本

上古 Win7，系统组件还有问题的那种。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Doctor-yoi** [comment]
dev版本采用.net 8.0，不建议在windows7及以下系统中使用

**Comment by HelloWRC** [comment]
考虑可能是.NET运行时内存泄漏（#91）导致的？可以用任务管理器检查一下。如果确实是内存泄漏产生的问题，可以考虑按照 https://github.com/HelloWRC/ClassIsland/blob/master/doc%2FInstallOnLegaceyOS.md 的指引修复这个问题。

如果这个问题不是内存泄漏所致，那有可能是渲染或者硬件方面的问题。解决这类问题超出了我的能力范围，很遗憾没办法解决。

**Comment by kaokao221** [comment]
> 考虑可能是.NET运行时内存泄漏（#91）导致的？可以用任务管理器检查一下。如果确实是内存泄漏产生的问题，可以考虑按照 https://github.com/HelloWRC/ClassIsland/blob/master/doc%2FInstallOnLegaceyOS.md 的指引修复这个问题。
> 
> 如果这个问题不是内存泄漏所致，那有可能是渲染或者硬件方面的问题。解决这类问题超出了我的能力范围，很遗憾没办法解决。

你说得对，但是花屏了怎么用任务管理器，不排除是VNC背锅，可以排查一下，需要注意的是花屏还有一种触发方式：在已经有正在运行的 CI 副本时再次打开exe，不排除内存泄露可能性，保留意见。
